# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partner_site'),
        ('course_metadata', '0056_auto_20170620_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, to='core.Currency'),
        ),
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
