# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0057_auto_20180830_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program_duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Course duration respected during automated programs generation.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='program_type',
            field=models.CharField(blank=True, help_text='Course special type to explicitly include/exclude during automated programs generation.', max_length=255, null=True),
        ),
    ]
