# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-03 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0058_auto_20180914_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='bundle_type',
            field=models.CharField(blank=True, choices=[('14', '14 hour bundle'), ('14:uspap', '14 hour USPAP bundle'), ('21', '21 hour bundle'), ('20', '20 hour bundle'), ('28', '28 hour bundle'), ('30', '30 hour bundle'), ('50', '50 hour bundle')], max_length=32, null=True),
        ),
    ]
