# Generated by Django 4.2.20 on 2026-06-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0351_bulkoperationtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='card_image_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use the card image field', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='card_image_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use the card image field', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
